### ISSUE TITLE
Emojis are not getting Rendered Properly 

### ISSUE THREAD

**Issue by Tibinsunny** [mufeedvh/binserve#1] opened 2020-10-01 09:54 UTC
Hey,
Unicoded Emojies like 😋 📙 are not Getting Rendered Properly.

Eg:
If I edit my "template_variables" in  binserve.json to 

 "template_variables": {
    "load_static": "/static/",
    "name": "This is test 😋"
  }

The Index page get rendered as 👇

![SS](https://user-images.githubusercontent.com/33937416/94794768-33da0700-0391-11eb-8344-7dd03e49180e.JPG)

And I believe this is something that should be fixed! Right?

OS:Windows 10 64Bit
Binserve used : binserve-v0.1.0-x86_64-pc-windows-gnu.exe

**Comment by mufeedvh** [comment] 2020-10-01 10:37
Hey @Tibinsunny,

**Nice Catch!** :heart: This is indeed something to be fixed. I think this issue is caused by [Handlebars](https://github.com/sunng87/handlebars-rust) because that's the package doing all the template rendering work so it seems like this should be fixed on their side although there might some hacky way I can sanitize the `template_variables` to support Unicode emojis. I will look into it!

Thanks for the detailed issue, I will resolve this ASAP! :+1:

**Comment by robjtede** [comment] 2020-10-13 23:47
Probably related to the UTF-8 flag I mentioned before.

**Comment by mufeedvh** [comment] 2020-10-14 17:40
Hello @robjtede,

It was indeed related to the UTF-8 flag `.prefer_utf8(true)`. 

![Screenshot from 2020-10-14 23-09-45](https://user-images.githubusercontent.com/26198477/96025175-66483180-0e72-11eb-978f-76cfbbc57b06.png)

Thank You @robjtede! :heart::raised_hands:
I will push the fix right away! :tada:

**Comment by mufeedvh** [comment] 2020-10-14 17:44
This issue has been fixed! :+1: 

Thank You @Tibinsunny @robjtede! :heart::raised_hands:

**Closed by mufeedvh** 2020-10-14 17:44 UTC
Labels: good first issue
